### ISSUE TITLE
AssetIdHash and other hidden properties

### ISSUE THREAD

**Issue by MartinSchmidt** [project-origin/registry#129]
We need to figure out how best to handle secret information that must be provable, something like a AssertId.

Funcationality required
- The AssertID must NOT be correlateable across multiple certificates
- The owner should be able to have some data in their wallet they can use to verify the data in the registry.
- The owner should be able to send this information to other parties when they transfer the certificate, if they so please.

Could it possible be a hash using a random salt ? 
So on the certificate one would publish the hash like SHA256(salt + AssertID) and if the owner then has the salt and AssertId be able to prove it?

I could also see this be relevant for gps position, address and the like, where one might choose to disclose it, but should not be forced to, but if one choses to share it, then it must be verifiable.

@Quacktiamauct  what do you think?

**Comment by Quacktiamauct** [comment]
I'm not sure I fully understand the requirements of the AssertID.

So is this to be a proof of ownership over a given certificate? So if a given certificate has a public value, such as the proposed hash, and then the owner has the 'AssertID' or 'password' producing the hash? But how would verification then take place as not to allow replay attacks?

It seems like you would need a proof of knowledge in some way. Also the transferring might be difficult, unless the public certificate is updated with the new AssertID.

**Comment by MartinSchmidt** [comment]
The assertId (in Denmark you can think of it as your Meter point - GSRN number), gps position or other information would be static on the certificate at the point of issuance, but the original owner might not want it to be public information. 

Then at the time of issuance we need to be able to add this information to the certificate, but in an obfuscated manner, so only those given the information can verify it, and this can then be transferred along through the wallets.

The ownership of individual slices are already dealt with using public-private keys.

The most primitive way i could think of would be a random value per certificate per property, which we could use to do a simple sha, so if you have AssetId "123" and a salt "267"   we simply publish a hash of SHA256(123267),  and send both the AssetId and Salt to your wallet. 

But I am not strong enough in cryptography to know if these are not secure enough, replay attacks, brute force.

The is mostly for now to be used by the owner itself to verify what they got.
Are you thinking if we need to be able to prove that all the AssetIds are equal without disclosing the information?

**Comment by Quacktiamauct** [comment]
In that case wouldn't it be a commitment to the AssertID, which is publicly attached to the certificate, sort of the same manner as the other commitments? Verification can then be done as a zero-knowledge proof, [example here](https://crypto.stackexchange.com/questions/74246/zero-knowledge-proof-for-opening-of-pedersen-commit-and-discrete-logarithm).

That would allow you to prove to others that you 'know' the assertID without showing it, but for transferring a certificate and such it can become a little complicated. We would have to look into that, since the original owner would know the value and we can't really delete that knowledge.

The apparent problem with hashing for me is that prove that you have the assertID, you would have to share the secret salt and assertID with the verifier. If the verifier is allowed knowledge of these, then it is of course not a problem, and then we can simply use something similar to passwords, and in that case salting and hashing might be the best.
But you of course can't just show the hash of the salt+assertID, since that is public in the first place.

**Comment by MartinSchmidt** [comment]
In regards to the AssetId I think the verifier is allowed to know it, otherwise what would it be a proof for?

When we come to  GPS position, I could of cause now see, maybe it could be relevant to show it is within a geographical area.. but this is up for speculation at this point, for now AssetID is the relevant part, and the verifier should be able to at the wish of the sender to know the value, and be able to verify it. 

So i guess a hash for now is sufficient, then we can always change this in the future i guess.

Would it be better to have a AssetId + CertId + salt? I guess this would make it harder to make some sort of brute force attack against a specific AssetId? but if we use a uuid as a salt, you wouldn't really be able to make a rainbow table anyway, two many possible answers.

**Comment by Quacktiamauct** [comment]
Adding the certificate ID to the hash binds the hash to the given certificate. This prevents people from reusing the assertID+salt for a different certificate, so that is probably a good idea. Salting should be a good enough shield against brute-forcing itself. The certificateID  could possibly act as the salt by, but more randomness definitely doesn't hurt security.

But is both the verifier and the sender aware of the assertID? In this context the prover is the one the secret assertID and the verifier want's to know if the prover actually has it.

Anyway, if we just want to couple some secret data with the public data, we can just put a hash of the secret(s) on the certificate. But you would only be able to verify it if you have the secrets.

**Comment by MartinSchmidt** [comment]
It is that both has it, not just prove it the other party has it, similar could be physical address on which the energy was produced.
I as a buyer might pay extra for knowing it is from a specific zipcode or specific address or wind turbine (AssetId) so i would want to know the actual information and be able to resell it aswell, but I still also want to be able to verify that it was true.

Only using the CertId as and hash would enable me to search other certificates for a given AssetId, since i can just try a specific assetId  on all certs in a registry, and that way correlate all other certificates from the same Asset, that would be bad.. so i guess for now we can use a generic way saying SHA256 (property + certid + salt) and use that.

**Comment by Quacktiamauct** [comment]
Ok, so both parties have access to the secrets, then a combination of `hash(assertID|certID|salt)`. You might also want to bind the assertID type too, such that can't be used for another one, so `hash("assertID"|assertID|certID|salt)`.

Yes given that a assertID is reusable between certificates you would be able to compare between, in the same manner that you would be able to for hashed passwords and in that case you need a random salt, since otherwise you can just enumerate all possible assertIDs to find it. I was more considering the case if a assertID didn't have a finite scope, then the amount of combinations could make it infeasible to do pure brute-forcing.

**Comment by MartinSchmidt** [comment]
Implemented in registry and wallet.
